
export const FETCHING_LOGIN = "FETCHING_LOGIN";
export const FETCHING_LOGIN_SUCCESS = "FETCHING_LOGIN_SUCCESS";
export const FETCHING_LOGIN_FAILURE = "FETCHING_LOGIN_FAILURE";


export const FETCHING_SIGNUP_REQUEST = "FETCHING_SIGNUP_REQUEST";
export const FETCHING_SIGNUP_SUCCESS = "FETCHING_SIGNUP_SUCCESS";
export const FETCHING_SIGNUP_FAILURE = "FETCHING_SIGNUP_FAILURE";

export const IS_LOADING = "IS_LOADING";

export const LOG_OUT = "LOG_OUT";
